### ISSUE TITLE
Dist-Zilla-Plugin-RequiresExternal tests fail in verbose mode

### ISSUE THREAD

**Issue by real-dam** [mjgardner/Dist-Zilla-Plugin-RequiresExternal#3]
We have the following bug reported to the Debian package of
Dist-Zilla-Plugin-RequiresExternal (https://bugs.debian.org/723932):

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

------8<-----------8<-----------8<-----------8<-----------8<-----

```
libdist-zilla-plugin-requiresexternal-perl fails to build with verbose tests 
enabled:

$ prove -vl
…

Test Summary Report
-------------------
t/test.t                   (Wstat: 0 Tests: 6 Failed: 3)
  Failed tests:  2-3, 5
  Parse errors: More than one plan found in TAP output
                Tests out of sequence.  Found (1) but expected (3)
                Tests out of sequence.  Found (2) but expected (4)
                Tests out of sequence.  Found (3) but expected (6)
                Bad plan.  You planned 3 tests but ran 6.
Files=21, Tests=36,  5 wallclock secs ( 0.05 usr  0.02 sys +  3.90 cusr  0.26 csys =  4.23 CPU)
Result: FAIL
Failed 1/21 test programs. 3/36 subtests failed.
make[1]: *** [test_dynamic] Error 255
```
------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  Damyan Ivanov,
  Debian Perl Group

**Comment by titanofold** [comment]
I've cloned this repo on Gentoo. Running `RELEASE_TESTING=1 make test`, `RELEASE_TESTING=1 prove -vl`, and `RELEASE_TESTING=1 prove -vb` resulted in successful test completions.

**Comment by real-dam** [comment]
Thanks for having a look. I am unable to reproduce this either :(

Perhaps in 2013 there was a problem in some dependency and that is now fixed.

Sorry for not re-checking before I forwarded the bug report, which I'll now close.
